project:
  type: website

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - icon: github
        href: https://github.com/MarieEtienne/stats-reminders
        aria-label: GitHub
      - text: "Instructions"
        href: instructions.qmd
      - text: "Two examples"
        menu:
        - text: "Basic quarto cross ref example"
          href: r_chapter.qmd
        - text: "Penguins example"
          href: Penguins_chapter.qmd       
        
        

    right:
      - text: "Linear Model"
        menu:
        - text : "Penguins"
          href : Linear_Model_1.qmd
        - text : "Badgers"
          href : Linear_Model_2.qmd 
      - text: "Factorial Analysis"
        menu:
        - pca.qmd
        - cca.qmd 
      - text: "Differential Equation"
        menu:
        - ode.qmd
        - pde.qmd 


format:
  html:
    theme: flatly
    linkcolor: "#c0392b"
    fontcolor: "#057174"
    css: mpe_pres_revealjs.css
    toc: true


    
